# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x  # Adjust the version as needed

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build  # Adjust the build command if needed

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build  # Adjust the build output folder if needed

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5  # Use a suitable version
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build  # The folder containing your build artifacts
          clean: true  # Remove existing files before deploying
